version: '3.8'

services:
  itmo-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_SEARCH_CX=${GOOGLE_SEARCH_CX}
    volumes:
      - ./app:/app
